---
- name: Distribute SSH keys among Hadoop nodes
  hosts: hadoop_cluster
  become: yes
  become_user: ubuntu
  tasks:
    - name: Fetch public key from Each NameNode
      slurp:
        src: "/home/ubuntu/.ssh/id_rsa.pub"
      register: ssh_pub_keys
      delegate_to: "{{ item }}"
      with_items: "{{ groups['hadoop_namenode'] }}"
      run_once: true

    - name: Ensure SSH directory exists
      file:
        path: "/home/ubuntu/.ssh"
        state: directory
        mode: '0700'

    - name: Add public keys to authorized_keys
      authorized_key:
        user: ubuntu
        key: "{{ item.content | b64decode }}"
        state: present
      loop: "{{ ssh_pub_keys.results }}"

