# ---
# - name: Install Java on all Nodes
#   hosts: all
#   become: true
#   tasks:
#     - name: Install OpenJDK 11
#       apt:
#         name: openjdk-11-jdk
#         state: present
#         update_cache: yes


---
- name: Install Java on all Nodes
  hosts: all
  become: true
  tasks:
    - name: Install OpenJDK 11
      apt:
        name: openjdk-11-jdk
        state: present
        update_cache: yes
      apt_key:
        url: https://adoptopenjdk.jfrog.io/adoptopenjdk/api/gpg/key/public
        state: present
      apt_repository:
        repo: https://adoptopenjdk.jfrog.io/adoptopenjdk/deb/
        state: present