---
- name: Update Hadoop Configuration
  hosts: all
  become: true
  vars:
    vars:
    hadoop_version: "hadoop-3.3.6"
    hadoop_home: "/usr/local/hadoop"
    java_home: "/usr/lib/jvm/java-1.11.0-openjdk-amd64"
    name_node_dir: "/home/ubuntu/data/nameNode"
    data_node_dir: "/home/ubuntu/data/dataNode"
    yarn_app_mapreduce_resource_mb: "512"
    yarn_app_map_resource_mb: "256"
    yarn_app_reduce_resource_mb: "256"
    replication_factor: "1"
    yarn_acl_enable: "0"
    yarn_nodemanager_resource_memory_mb: "2560"
    yarn_scheduler_maximum_allocation_mb: "2048"
    yarn_scheduler_minimum_allocation_mb: "512"
    yarn_nodemanager_vmem_check_enabled: "false"
    namenode_hostname: "Master1"

  tasks:
    - name: Ensure necessary packages are installed (if needed)
      apt:
        name:
          - wget
          - tar
        state: present
        update_cache: yes

    - name: Backup current Hadoop directory
      command: mv {{ hadoop_home }} {{ hadoop_home }}_backup_{{ ansible_date_time.iso8601 }}
      when: ansible_date_time.iso8601 is defined

    - name: Ensure /etc/profile.d/ directory exists
      file:
        path: /etc/profile.d
        state: directory
        mode: '0755'

    - name: Set Hadoop environment variables
      template:
        src: "templates/hadoop/hadoop.sh.j2"
        dest: "/etc/profile.d/hadoop.sh"
        mode: '0755'

    - name: Template Hadoop configuration files
      template:
        src: "templates/hadoop/{{ item.src }}"
        dest: "{{ hadoop_home }}/etc/hadoop/{{ item.dest }}"
      loop:
        - { src: 'core-site.xml.j2', dest: 'core-site.xml' }
        - { src: 'hdfs-site.xml.j2', dest: 'hdfs-site.xml' }
        - { src: 'yarn-site.xml.j2', dest: 'yarn-site.xml' }
        - { src: 'mapred-site.xml.j2', dest: 'mapred-site.xml' }

    - name: Template Hadoop environment file
      template:
        src: "templates/hadoop/hadoop-env.sh.j2"
        dest: "{{ hadoop_home }}/etc/hadoop/hadoop-env.sh"

    - name: Template .profile
      template:
        src: "templates/profile.j2"
        dest: "/home/ubuntu/.profile"
        owner: ubuntu
        group: ubuntu
        mode: '0644'

    - name: Template .bashrc
      template:
        src: "templates/bashrc.j2"
        dest: "/home/ubuntu/.bashrc"
        owner: ubuntu
        group: ubuntu
        mode: '0644'

    - name: Template workers file
      template:
        src: "templates/hadoop/workers.j2"
        dest: "{{ hadoop_home }}/etc/hadoop/workers"
        owner: ubuntu
        group: ubuntu
        mode: '0644'

# Separate play for formatting NameNode if needed
- name: Format the HDFS NameNode (if necessary)
  hosts: Master1
  become: true
  tasks:
    - name: Run 'hdfs namenode -format' on NameNode (if necessary)
      command: hdfs namenode -format
      when: "ansible_date_time.iso8601 is defined"  # Only format if necessary
