---
- name: Install and Configure Hadoop
  hosts: hadoop_cluster
  become: true
  vars:
    hadoop_version: "hadoop-3.3.6"
    hadoop_home: "/usr/local/hadoop"
    java_home: "/usr/lib/jvm/java-1.11.0-openjdk-amd64"
    name_node_dir: "/home/ubuntu/data/nameNode"
    data_node_dir: "/home/ubuntu/data/dataNode"
    yarn_app_mapreduce_resource_mb: "512"
    yarn_app_map_resource_mb: "256"
    yarn_app_reduce_resource_mb: "256"
    replication_factor: "1"
    yarn_acl_enable: "0"
    yarn_nodemanager_resource_memory_mb: "2560"
    yarn_scheduler_maximum_allocation_mb: "2048"
    yarn_scheduler_minimum_allocation_mb: "512"
    yarn_nodemanager_vmem_check_enabled: "false"
    hadoop_security_authentication: "kerberos"
    hadoop_security_authorization_bool: "true"
    yarn_token_renew_interval: "3600000"
    yarn_token_max_lifetime: "604800000"
    namenode_hostname: "Master1"
  tasks:
    - name: Ensure /etc/profile.d/ directory exists
      file:
        path: /etc/profile.d
        state: directory
        mode: '0755'

    - name: Set Hadoop environment variables
      template:
        src: "templates/hadoop/hadoop.sh.j2"
        dest: "/etc/profile.d/hadoop.sh"
        mode: '0755'

    - name: Template Hadoop configuration files
      template:
        src: "templates/hadoop/{{ item.src }}"
        dest: "{{ hadoop_home }}/etc/hadoop/{{ item.dest }}"
      loop:
        - { src: 'core-site.xml.j2', dest: 'core-site.xml' }
        - { src: 'hdfs-site.xml.j2', dest: 'hdfs-site.xml' }
        - { src: 'yarn-site.xml.j2', dest: 'yarn-site.xml' }
        - { src: 'mapred-site.xml.j2', dest: 'mapred-site.xml' }
        - { src: 'ssl-client.xml.j2', dest: 'ssl-client.xml' }
        - { src: 'ssl-server.xml.j2', dest: 'ssl-server.xml' }

    - name: Template Hadoop environment file
      template:
        src: "templates/hadoop/hadoop-env.sh.j2"
        dest: "{{ hadoop_home }}/etc/hadoop/hadoop-env.sh"

    - name: Template .profile
      template:
        src: "templates/profile.j2"
        dest: "/home/ubuntu/.profile"
        owner: ubuntu
        group: ubuntu
        mode: '0644'

    - name: Template .bashrc
      template:
        src: "templates/bashrc.j2"
        dest: "/home/ubuntu/.bashrc"
        owner: ubuntu
        group: ubuntu
        mode: '0644'

    - name: Create workers file
      template:
        src: "templates/hadoop/workers.j2"
        dest: "{{ hadoop_home }}/etc/hadoop/workers"
        owner: ubuntu
        group: ubuntu
        mode: '0644'
    # # Separate play for formatting NameNode
    # - name: Format the HDFS NameNode
    #   hosts: Master1
    #   become: true
    #   tasks:
    #     - name: Run 'hdfs namenode -format' on NameNode
    #       command: hdfs namenode -format
    #
