---
- name: Update /etc/hosts for Hadoop cluster communication
  hosts: all
  become: yes
  tasks:
    - name: Gather hosts facts
      setup:

    - name: Build hosts entries
      set_fact:
        host_entries: |
          {% for host in groups['all'] %}
          {{ hostvars[host]['ansible_default_ipv4']['address'] }} {{ host }}
          {% endfor %}

    - name: Ensure /etc/hosts has correct entries
      lineinfile:
        path: /etc/hosts
        create: yes
        state: present
        line: "{{ item }}"
      with_items: "{{ host_entries.split('\n') }}"
      when: item != ''

